---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure directories to export exist
  ansible.builtin.file:  # noqa 208
    path: "{{ item.strip().split()[0] }}"
    state: directory
    owner: nobody
    group: nogroup
  with_items: "{{ nfs_exports }}"

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs

- name: Ensure nfs is running.
  service: "name={{ nfs_server_daemon }} state=started enabled=yes"
  when: nfs_exports|length