---
- hosts: localhost
  gather_facts: true
  #roles:
  #  - nfs

  tasks:
    - name: Get nodes
      command: kubectl get nodes
      register: current_nodes
      changed_when: false

    - name: Print nodes
      debug:
        msg: "{{ current_nodes.stdout }}"

    - name: Update traefik
      import_tasks: local-ansible/traefik-helm.yml

    - name: include Crossplane
      import_tasks: local-ansible/crossplane-helm.yml

    - name: include Argo CD
      import_tasks: local-ansible/argocd-helm.yml

    - name: include Bitnami
      import_tasks: local-ansible/bitnami-helm.yml

    - name: include cert-manager
      import_tasks: local-ansible/jetstack-helm.yml

#    - name: include rancher
#      import_tasks: local-ansible/rancher-helm.yml
