---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Get nodes
      command: kubectl get nodes
      register: current_nodes
      changed_when: false

    - name: Print nodes
      debug:
        msg: "{{ current_nodes.stdout }}"

    - name: include Crossplane
      import_tasks: local/crossplane-helm.yml

    - name: include Argo CD
      import_tasks: local/argocd-helm.yml
    
    - name: include Bitnami
      import_tasks: local/bitnami-helm.yml